# Generated by Django 5.2.16 on 2026-08-05 11:41

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Recorded sign gesture video clip.', upload_to=app.models._clip_upload_path)),
                ('gesture', models.CharField(blank=True, help_text='Arabic word/phrase detected by the model.', max_length=200)),
                ('dialect', models.CharField(default='Saudi Arabic Sign Language', help_text='Regional sign dialect used during this clip.', max_length=100)),
                ('confidence', models.FloatField(default=0.0, help_text='Model prediction confidence (0.0 – 1.0).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Translation Clip',
                'verbose_name_plural': 'Translation Clips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_sentence', models.TextField(blank=True, help_text='AI-reconstructed Arabic output sentence.')),
                ('english_sentence', models.TextField(blank=True, help_text='AI-reconstructed English translation.')),
                ('dialect', models.CharField(default='Saudi Arabic Sign Language', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clips', models.ManyToManyField(blank=True, help_text='Individual gesture clips that formed this sentence.', related_name='sessions', to='app.translationclip')),
            ],
            options={
                'verbose_name': 'Translation Session',
                'verbose_name_plural': 'Translation Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
